-- ==============================================================================
-- AegisCortex AI - 02_schema_and_tables.sql
-- Table DDLs for Structured EHR, MDM Golden Records, Commercial Alignment,
-- Formulary / PA Denials, and Document Chunks
-- ==============================================================================

USE DATABASE AEGIS_CORTEX_DB;
USE SCHEMA RAW;

-- 1. Patients Table with Dynamic PHI Masking
CREATE OR REPLACE TABLE AEGIS_CORTEX_DB.RAW.PATIENTS (
    PATIENT_ID VARCHAR(32) PRIMARY KEY,
    FIRST_NAME VARCHAR(64) MASKING POLICY AEGIS_CORTEX_DB.RAW.PHI_MASK_STRING,
    LAST_NAME VARCHAR(64) MASKING POLICY AEGIS_CORTEX_DB.RAW.PHI_MASK_STRING,
    GENDER VARCHAR(16),
    BIRTH_DATE DATE,
    AGE INTEGER,
    CITY VARCHAR(64),
    STATE VARCHAR(32),
    ZIP_CODE VARCHAR(16) MASKING POLICY AEGIS_CORTEX_DB.RAW.PHI_MASK_STRING,
    BLOOD_GROUP VARCHAR(8),
    PRIMARY_PHYSICIAN VARCHAR(128),
    CHRONIC_CONDITIONS VARCHAR(512),
    ACTIVE_MEDICATIONS VARCHAR(1024),
    RISK_DECIL_SCORE INTEGER,
    RISK_STRATIFICATION VARCHAR(64),
    INSURANCE_PLAN VARCHAR(128),
    INGESTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 2. Encounters Table
CREATE OR REPLACE TABLE AEGIS_CORTEX_DB.RAW.ENCOUNTERS (
    ENCOUNTER_ID VARCHAR(32) PRIMARY KEY,
    PATIENT_ID VARCHAR(32) REFERENCES AEGIS_CORTEX_DB.RAW.PATIENTS(PATIENT_ID),
    ENCOUNTER_DATE DATE,
    ENCOUNTER_TYPE VARCHAR(64),
    CHIEF_COMPLAINT VARCHAR(256),
    PROVIDER_NAME VARCHAR(128),
    FACILITY_NAME VARCHAR(128),
    DIAGNOSIS_CODES VARCHAR(128),
    DISCHARGE_SUMMARY TEXT,
    INGESTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 3. LOINC Lab Results Table
CREATE OR REPLACE TABLE AEGIS_CORTEX_DB.RAW.LAB_RESULTS (
    LAB_ID VARCHAR(32) PRIMARY KEY,
    PATIENT_ID VARCHAR(32) REFERENCES AEGIS_CORTEX_DB.RAW.PATIENTS(PATIENT_ID),
    COLLECTION_DATE DATE,
    LOINC_CODE VARCHAR(32),
    TEST_NAME VARCHAR(128),
    NUMERIC_VALUE FLOAT,
    UNITS VARCHAR(32),
    REFERENCE_RANGE VARCHAR(64),
    INTERPRETATION VARCHAR(256),
    ABNORMAL_FLAG VARCHAR(8),
    ORDERING_PHYSICIAN VARCHAR(128),
    INGESTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 4. Claims & Billing Table
CREATE OR REPLACE TABLE AEGIS_CORTEX_DB.RAW.CLAIMS (
    CLAIM_ID VARCHAR(32) PRIMARY KEY,
    PATIENT_ID VARCHAR(32) REFERENCES AEGIS_CORTEX_DB.RAW.PATIENTS(PATIENT_ID),
    SERVICE_DATE DATE,
    CPT_CODE VARCHAR(32),
    SERVICE_DESCRIPTION VARCHAR(256),
    TOTAL_CHARGES FLOAT,
    PAID_AMOUNT FLOAT,
    CLAIM_STATUS VARCHAR(32),
    INGESTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- ==============================================================================
-- PHARMA ENTERPRISE CORE: MDM, ALIGNMENT, MARKET ACCESS & PRESCRIPTION EVENTS
-- ==============================================================================

-- 5. Healthcare Organization (HCO / IDN) Master Table
CREATE OR REPLACE TABLE AEGIS_CORTEX_DB.RAW.MDM_HCO_MASTER (
    HCO_ID VARCHAR(32) PRIMARY KEY,
    HCO_NAME VARCHAR(256) NOT NULL,
    HCO_TYPE VARCHAR(128) NOT NULL,           -- 'Academic Integrated Delivery Network (IDN)', 'Safety Net / 340B'
    TIN VARCHAR(32),
    PARENT_IDN_NAME VARCHAR(256),
    CITY VARCHAR(64),
    STATE VARCHAR(32),
    ZIP5 VARCHAR(10),
    BEDS_COUNT INTEGER,
    PT_COMMITTEE_STATUS VARCHAR(128),         -- 'Preferred (Tier 2 Biologics)', 'Step-Therapy Required'
    PROTOCOL_RESTRICTION_LEVEL VARCHAR(32),   -- 'Low', 'Moderate', 'High'
    INGESTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 6. Healthcare Provider (HCP) Master Data Management Table
CREATE OR REPLACE TABLE AEGIS_CORTEX_DB.RAW.MDM_HCP_MASTER (
    HCP_ID VARCHAR(32) PRIMARY KEY,
    NPI VARCHAR(10) UNIQUE NOT NULL,
    FIRST_NAME VARCHAR(64) NOT NULL,
    LAST_NAME VARCHAR(64) NOT NULL,
    PRIMARY_SPECIALTY VARCHAR(128) NOT NULL,   -- 'Dermatology', 'Rheumatology', 'Nephrology'
    TAXONOMY_CODE VARCHAR(32) NOT NULL,       -- e.g. '207N00000X'
    PRACTICE_ADDRESS VARCHAR(256),
    CITY VARCHAR(64),
    STATE VARCHAR(32),
    ZIP5 VARCHAR(10),
    DEA_NUMBER VARCHAR(32),
    AMA_ID VARCHAR(32),
    IDN_AFFILIATION_ID VARCHAR(32) REFERENCES AEGIS_CORTEX_DB.RAW.MDM_HCO_MASTER(HCO_ID),
    PRESCRIBER_DECILE INTEGER,                 -- 1 to 10
    PEER_RANKING VARCHAR(128),
    INGESTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 7. Commercial Sales Territory Dimension
CREATE OR REPLACE TABLE AEGIS_CORTEX_DB.RAW.DIM_TERRITORY (
    TERRITORY_ID VARCHAR(32) PRIMARY KEY,     -- e.g. 'US-PA-PHILLY-01'
    REGION_ID VARCHAR(32),                    -- 'REG-NORTHEAST'
    AREA_ID VARCHAR(32),                      -- 'AREA-MIDATLANTIC'
    TERRITORY_NAME VARCHAR(128),
    ASSIGNED_REP_NAME VARCHAR(128),
    TARGET_CALL_CAPACITY INTEGER,
    QUOTA_TRX INTEGER,
    INGESTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 8. HCP Territory Alignment & Account Opportunity Index (AOI)
CREATE OR REPLACE TABLE AEGIS_CORTEX_DB.RAW.MAP_HCP_TERRITORY_ALIGNMENT (
    HCP_ID VARCHAR(32) REFERENCES AEGIS_CORTEX_DB.RAW.MDM_HCP_MASTER(HCP_ID),
    TERRITORY_ID VARCHAR(32) REFERENCES AEGIS_CORTEX_DB.RAW.DIM_TERRITORY(TERRITORY_ID),
    ACCOUNT_OPPORTUNITY_INDEX FLOAT,          -- Scale 0-100 composite potential
    TARGET_DECILE INTEGER,                    -- Target decile priority (1-10)
    CALL_FREQUENCY_ANNUAL INTEGER,            -- Required annual details (e.g. 24 visits)
    TRAVEL_IMPEDANCE_SCORE FLOAT,             -- Drive time friction penalty (1.0 = optimal)
    CONVERSION_VELOCITY_DAYS INTEGER,         -- Survival curve expected days to first script
    PRIMARY KEY (HCP_ID, TERRITORY_ID)
);

-- 9. PBM & Health Plan Formulary Placement Coverage
CREATE OR REPLACE TABLE AEGIS_CORTEX_DB.RAW.FACT_FORMULARY_TIER_COVERAGE (
    PLAN_ID VARCHAR(32),
    PAYER_NAME VARCHAR(128),
    PBM_NAME VARCHAR(128),
    LOB VARCHAR(64),                          -- 'Commercial', 'Medicare Advantage', 'Managed Medicaid'
    NDC_CODE VARCHAR(16),
    DRUG_BRAND VARCHAR(128),
    TIER_LEVEL VARCHAR(64),                   -- 'Tier 1 Generic', 'Tier 2 Preferred Brand', 'Tier 4 Specialty'
    PA_REQUIRED_FLAG VARCHAR(1),              -- 'Y' or 'N'
    STEP_THERAPY_REQUIRED_FLAG VARCHAR(1),    -- 'Y' or 'N'
    QUANTITY_LIMIT_FLAG VARCHAR(1),
    COPAY_AVG_USD FLOAT,
    PRIMARY KEY (PLAN_ID, NDC_CODE)
);

-- 10. Longitudinal Fact Prescription Events
CREATE OR REPLACE TABLE AEGIS_CORTEX_DB.RAW.FACT_PRESCRIPTION_EVENTS (
    PRESCRIPTION_EVENT_ID VARCHAR(64) PRIMARY KEY,
    PATIENT_TOKEN VARCHAR(64) NOT NULL,       -- De-identified cryptographic token
    PRESCRIBING_NPI VARCHAR(10) NOT NULL REFERENCES AEGIS_CORTEX_DB.RAW.MDM_HCP_MASTER(NPI),
    ENCOUNTER_ID VARCHAR(64),
    AUTHORED_DATE DATE NOT NULL,
    ICD10_PRIMARY_DIAGNOSIS VARCHAR(16) NOT NULL, -- e.g. 'L40.0' (Plaque Psoriasis)
    RXNORM_CUI VARCHAR(16) NOT NULL,          -- e.g. '2059343' (Risankizumab)
    NDC_CODE VARCHAR(16) NOT NULL,            -- e.g. '0074-1050-01'
    DRUG_BRAND VARCHAR(128) NOT NULL,
    DRUG_CLASS VARCHAR(128) NOT NULL,         -- 'IL-23 Biologic', 'TNF Inhibitor'
    DOSAGE_MAGNITUDE FLOAT NOT NULL,
    DOSAGE_UNIT VARCHAR(16) NOT NULL,
    FREQUENCY_DAYS INTEGER NOT NULL,
    REFILLS_AUTHORIZED INTEGER NOT NULL,
    PAYER_ID VARCHAR(32),
    CLAIM_STATUS VARCHAR(32),                 -- 'PAID', 'REJECTED_PA', 'REJECTED_COPAY'
    COPAY_COINSURANCE_USD FLOAT,
    TERRITORY_ID VARCHAR(32) REFERENCES AEGIS_CORTEX_DB.RAW.DIM_TERRITORY(TERRITORY_ID),
    ETL_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 11. Prior Authorization (PA) Denial Diagnostics
CREATE OR REPLACE TABLE AEGIS_CORTEX_DB.RAW.FACT_PA_DENIALS (
    DENIAL_ID VARCHAR(32) PRIMARY KEY,
    CLAIM_ID VARCHAR(64),
    PATIENT_TOKEN VARCHAR(64),
    PRESCRIBING_NPI VARCHAR(10) REFERENCES AEGIS_CORTEX_DB.RAW.MDM_HCP_MASTER(NPI),
    NDC_CODE VARCHAR(16),
    DRUG_BRAND VARCHAR(128),
    DENIAL_DATE DATE,
    REJECTION_CODE VARCHAR(32),               -- e.g. 'X12-75', 'NCPDP-88'
    REJECTION_REASON VARCHAR(512),
    RECOVERABLE_REVENUE_USD FLOAT,
    APPEAL_STATUS VARCHAR(64),                -- 'OVERTURNED', 'IN_REVIEW', 'PEER_TO_PEER_SCHEDULED'
    TERRITORY_ID VARCHAR(32) REFERENCES AEGIS_CORTEX_DB.RAW.DIM_TERRITORY(TERRITORY_ID),
    INGESTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 12. Representative Detailing Call Activity (PDMA Compliant)
CREATE OR REPLACE TABLE AEGIS_CORTEX_DB.RAW.FACT_CALL_ACTIVITY (
    CALL_ID VARCHAR(32) PRIMARY KEY,
    HCP_ID VARCHAR(32) REFERENCES AEGIS_CORTEX_DB.RAW.MDM_HCP_MASTER(HCP_ID),
    REP_NAME VARCHAR(128),
    TERRITORY_ID VARCHAR(32) REFERENCES AEGIS_CORTEX_DB.RAW.DIM_TERRITORY(TERRITORY_ID),
    CALL_DATE DATE,
    INTERACTION_TYPE VARCHAR(64),             -- 'In-Person Detailing', 'Medical Education Lunch'
    DETAIL_PRIORITY VARCHAR(256),
    SAMPLES_DROPPED_QTY INTEGER,
    LOT_NUMBER VARCHAR(64),
    SIGNATURE_VERIFIED VARCHAR(1),
    INGESTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 13. Document Chunks Table with CHANGE_TRACKING for Cortex Search
USE SCHEMA TRANSFORMED;

CREATE OR REPLACE TABLE AEGIS_CORTEX_DB.TRANSFORMED.CLINICAL_DOC_CHUNKS (
    CHUNK_ID VARCHAR(64) PRIMARY KEY,
    FILE_NAME VARCHAR(256),
    DOC_TITLE VARCHAR(256),        -- Human readable title e.g. 'FDA Metformin Package Insert'
    DOC_TYPE VARCHAR(64),          -- 'CLINICAL_NOTE', 'FDA_INSERT', 'HEDIS_GUIDELINE'
    PATIENT_ID VARCHAR(32),        -- NULL for general guidelines/FDA inserts
    SECTION_NAME VARCHAR(128),     -- e.g. 'CONTRAINDICATIONS', 'DOSAGE', 'LAB_ORDERS'
    PAGE_NUMBER INTEGER,
    CHUNK_TEXT TEXT,
    CHUNK_HASH VARCHAR(64),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
) CHANGE_TRACKING = TRUE
COMMENT = 'Processed document chunks indexed for Cortex Search vector retrieval';

