-- ==============================================================================
-- AegisCortex AI - 06_load_large_synthetic_data.sql
-- Loads the 10,000-patient synthetic lakehouse cohort into Snowflake RAW schema
-- ==============================================================================

USE DATABASE AEGIS_CORTEX_DB;
USE SCHEMA RAW;
USE WAREHOUSE COMPUTE_WH;

-- 1. Create Internal Stage for Large Synthetic Datasets
CREATE OR REPLACE STAGE AEGIS_CORTEX_DB.RAW.STAGE_SYNTHETIC_LARGE
    ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE')
    FILE_FORMAT = (TYPE = 'CSV', FIELD_OPTIONALLY_ENCLOSED_BY = '"', SKIP_HEADER = 1);

-- Note: Upload CSV files from data/synthetic_large/ using SnowSQL or Snowflake Python Connector:
-- PUT file://./data/synthetic_large/*.csv @AEGIS_CORTEX_DB.RAW.STAGE_SYNTHETIC_LARGE AUTO_COMPRESS=TRUE;

-- 2. Truncate / Copy into Core Tables
TRUNCATE TABLE IF EXISTS AEGIS_CORTEX_DB.RAW.PATIENTS;
COPY INTO AEGIS_CORTEX_DB.RAW.PATIENTS (
    PATIENT_ID, FIRST_NAME, LAST_NAME, GENDER, BIRTH_DATE, AGE, CITY, STATE, ZIP_CODE,
    BLOOD_GROUP, PRIMARY_PHYSICIAN, CHRONIC_CONDITIONS, ACTIVE_MEDICATIONS,
    RISK_DECIL_SCORE, RISK_STRATIFICATION, INSURANCE_PLAN
)
FROM (
    SELECT $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16
    FROM @AEGIS_CORTEX_DB.RAW.STAGE_SYNTHETIC_LARGE/patients.csv
)
FILE_FORMAT = (TYPE = 'CSV', FIELD_OPTIONALLY_ENCLOSED_BY = '"', SKIP_HEADER = 1)
ON_ERROR = 'CONTINUE';

-- 3. Copy Lab Results (132k+ LOINC Labs)
TRUNCATE TABLE IF EXISTS AEGIS_CORTEX_DB.RAW.LAB_RESULTS;
COPY INTO AEGIS_CORTEX_DB.RAW.LAB_RESULTS (
    LAB_ID, PATIENT_ID, COLLECTION_DATE, LOINC_CODE, TEST_NAME, NUMERIC_VALUE,
    UNITS, REFERENCE_RANGE, ABNORMAL_FLAG, ORDERING_PHYSICIAN
)
FROM @AEGIS_CORTEX_DB.RAW.STAGE_SYNTHETIC_LARGE/lab_results.csv
FILE_FORMAT = (TYPE = 'CSV', FIELD_OPTIONALLY_ENCLOSED_BY = '"', SKIP_HEADER = 1)
ON_ERROR = 'CONTINUE';

-- 4. Copy Encounters (40k+ Visits)
TRUNCATE TABLE IF EXISTS AEGIS_CORTEX_DB.RAW.ENCOUNTERS;
COPY INTO AEGIS_CORTEX_DB.RAW.ENCOUNTERS (
    ENCOUNTER_ID, PATIENT_ID, ENCOUNTER_DATE, ENCOUNTER_TYPE, CHIEF_COMPLAINT,
    PROVIDER_NAME, FACILITY_NAME, DIAGNOSIS_CODES, DISCHARGE_SUMMARY
)
FROM @AEGIS_CORTEX_DB.RAW.STAGE_SYNTHETIC_LARGE/encounters.csv
FILE_FORMAT = (TYPE = 'CSV', FIELD_OPTIONALLY_ENCLOSED_BY = '"', SKIP_HEADER = 1)
ON_ERROR = 'CONTINUE';

-- 5. Copy Claims (40k+ Claims)
TRUNCATE TABLE IF EXISTS AEGIS_CORTEX_DB.RAW.CLAIMS;
COPY INTO AEGIS_CORTEX_DB.RAW.CLAIMS (
    CLAIM_ID, PATIENT_ID, SERVICE_DATE, CPT_CODE, SERVICE_DESCRIPTION,
    TOTAL_CHARGES, PAID_AMOUNT, CLAIM_STATUS
)
FROM @AEGIS_CORTEX_DB.RAW.STAGE_SYNTHETIC_LARGE/claims.csv
FILE_FORMAT = (TYPE = 'CSV', FIELD_OPTIONALLY_ENCLOSED_BY = '"', SKIP_HEADER = 1)
ON_ERROR = 'CONTINUE';

-- 6. Verification
SELECT 'PATIENTS' AS TBL, COUNT(*) AS CNT FROM AEGIS_CORTEX_DB.RAW.PATIENTS
UNION ALL
SELECT 'LAB_RESULTS', COUNT(*) FROM AEGIS_CORTEX_DB.RAW.LAB_RESULTS
UNION ALL
SELECT 'ENCOUNTERS', COUNT(*) FROM AEGIS_CORTEX_DB.RAW.ENCOUNTERS
UNION ALL
SELECT 'CLAIMS', COUNT(*) FROM AEGIS_CORTEX_DB.RAW.CLAIMS;
